app/_locales/en_US/messages.json
app/background/api/localeAPI.js
app/containers/newTab.js
app/manifest.dev.json
app/manifest.prod.json
scripts/tasks.js
test/app/background/api/localeAPITest.js
test/testData.js

Test Plan: yarn test -- --grep="locale API"

Use chrome.i18n

---

BUILD.gn
py-scripts/build-brave-extension.py

Fixes x86 build issue of `out` and `out_x86` dirs.

fixes x86 build

---

BUILD.gn
app/_locales/uk/messages.json
app/components/braveShields/braveShieldsStats.tsx
py-scripts/build-brave-extension.py
py-scripts/copy-brave-extension-localization.py

Modifications of build scripts and  tsx to use chrome.i18n localization. 
This is not a final PR on this task, it is intended to flush current modifications into the master branch. Remaining task is to modify other hard-coded strings to localized.

Extension localization

---

app/components/braveShields/braveShieldsControls.tsx
package.json
test/app/components/braveShields/braveShieldsControlsTest.tsx
test/app/components/braveShields/braveShieldsFooterTest.tsx
test/app/components/braveShields/braveShieldsHeaderTest.tsx
test/app/components/braveShields/braveShieldsStatsTest.tsx
yarn.lock

This reverts commit 330333dc2458b240f6eb278142be26f2dc146cf7, reversing
changes made to fd3d4a7b9fc206649d504b8616f095
This has been on master for a while so reverting the original PR.
https://github.com/brave/brave-extension/pull/16
ff9376d03a.

Revert "Merge pull request #16 from brave/test-fixes"

---

py-scripts/build-brave-extension.py

Reverts brave/brave-extension#30

Revert "Change node builder from npm to yarn"

---

BUILD.gn
app/background/api/browserActionAPI.ts
test/app/background/api/browserActionAPITest.ts

Fix https://github.com/brave/brave-browser/issues/460

Fix icon paths used in setIcon

---

.travis.yml
README.md
appveyor.yml
scripts/tests.js

see convo in https://bravesoftware.slack.com/archives/C7VLGSR55/p1530192665000124

replace yarn with npm

---

app/_locales/hu/messages.json
app/_locales/id/messages.json
app/_locales/ko/messages.json
app/_locales/sv/messages.json
package-lock.json
package.json

Related to issue brave/brave-browser#292
Related PRs:
https://github.com/brave/brave-browser/pull/571
https://github.com/brave/brave-core/pull/257
https://github.com/brave/brave-extension/pull/50

Update strings and update deps for C68 upgrade

---

app/components/braveShields/braveShieldsControls.tsx

closes brave/brave-browser#399

remove option for safe browsing

---

app/manifest.dev.json
app/manifest.prod.json

closes https://github.com/brave/brave-browser/issues/691

disallow unsafe-eval for scripts and wildcard for styles in manifest file

---

app/manifest.dev.json

follow-up of https://github.com/brave/brave-extension/pull/55
cc @diracdeltas @Snuupy

re-allow inline scripts for dev mode

---

scripts/build.js
scripts/dev.js
scripts/tasks.js

fix https://github.com/brave/brave-browser/issues/1102
after https://github.com/brave/brave-extension/commit/48293869a7914b5f5f75292495b73d3dbb23f5bf `npm run dev` stopped working.
Test Plan:
`npm run dev` should compile

find the correct path for dev mode

---

app/background/reducers/shieldsPanelReducer.ts
app/manifest.dev.json
app/manifest.prod.json

Fixes https://github.com/brave/brave-browser/issues/729

Clear site cookies and local storage immediately on changing 'block cookies' setting to 'block'

---

test/app/background/api/shieldsAPITest.ts
test/testData.ts

fix https://github.com/brave/brave-browser/issues/1487
test plan: `npm run test-unit`

fix broken tests due to missing mock in chrome.extension.inIncognitoContext

---

app/background/events/runtimeEvents.ts

Fix https://github.com/brave/brave-browser/issues/1437

Workaround onStartup not being called for incognito

---

app/background/events/runtimeEvents.ts

Fix https://github.com/brave/brave-browser/issues/1587

Fix lint error

---

.gitignore
.travis.yml
package-lock.json
package.json
scripts/tests.js

fix https://github.com/brave/brave-browser/issues/1846
fix https://github.com/brave/brave-browser/issues/1845

Package updates to fix security issues

---

app/components/braveShields/interfaceControls.tsx

follow-up of #78 
STR:
1. go to https://twitter.com/brianbondy
2. check there are 5 ads/trackers blocked
3. click the arrow down to go to resources blocked list
4. there should be 5 resources

properly merge ads and trackers blocked list

---

app/components/braveShields/interfaceControls.tsx
app/components/braveShields/privacyControls.tsx
app/helpers/shieldsUtils.ts
test/app/components/braveShields/interfaceControlsTest.tsx
test/app/components/braveShields/privacyControlsTest.tsx

fix https://github.com/brave/brave-browser/issues/1951
Test Plan: covered by automated tests

set stats to 99+ if resource is above that number

---

app/components/braveShields/interfaceControls.tsx
app/components/braveShields/privacyControls.tsx
package-lock.json
package.json

closes https://github.com/brave/brave-browser/issues/1957
Test Plan:
when stat is 0 you shouldn't be able to see resources blocked list

disallow click event when stats are 0
