brave/brave-extension

test/setupApp.js

Running `yarn test` outputs a warning message from React that this change suppresses:
```
Warning: React depends on requestAnimationFrame. Make sure that you load a polyfill in older browsers. http://fb.me/react-polyfills
```

suppress React rAF warning while testing

---

app/components/braveShields/braveShieldsControls.tsx
package.json
test/app/components/braveShields/braveShieldsControlsTest.tsx
test/app/components/braveShields/braveShieldsFooterTest.tsx
test/app/components/braveShields/braveShieldsHeaderTest.tsx
test/app/components/braveShields/braveShieldsStatsTest.tsx
yarn.lock

fix https://github.com/brave/brave-browser/issues/147
Covered:
* Update brave-ui to v0.6.0 (latest)
* Update type definitions in components testing
* Mocks CSS imports in all unit tests (needs security audit)
* Fix missing bracket in `braveShieldsControlsTest.tsx`
Test Plan:
* `yarn test-unit` should pass, including `tsx` files testing

unblock components unit testing

---

app/components/braveShields/braveShieldsControls.tsx
package.json
test/app/components/braveShields/braveShieldsControlsTest.tsx
test/app/components/braveShields/braveShieldsFooterTest.tsx
test/app/components/braveShields/braveShieldsHeaderTest.tsx
test/app/components/braveShields/braveShieldsStatsTest.tsx
yarn.lock

This re-includes merge commit 330333dc2458b240f6eb278142be26f2dc146cf7 made in #16 and reverted by a10c297 in #17.
Copying test plan from original PR (#16):
* ~~Update brave-ui to v0.6.0 (latest)~~ we're now using v0.7.0
* Update type definitions in components testing
* Mocks CSS imports in all unit tests ~~(needs security audit)~~ (done)
* Fix missing bracket in `braveShieldsControlsTest.tsx`
fix brave/brave-browser#158
**For the record:** issue was caused because as of v0.6.0 brave-ui was refactored to use vanilla CSS. postCSS plugin in brave-extension was then changing styles name causing components to be unstyled.
Test Plan:
* `yarn test-unit` should pass, including `tsx` files testing
* ✨ [new] ✨ **Ensure CSS is loaded in the shields panel**

re-enable components testing, fix broken styles in shields panel

---

BUILD.gn

If directly copying into framework bundle, mac_framework_bundle template
can cause error when framework bundle version is used.
When bundle version is newly added or changed to different version, mac_framework_bundle
template tries to removes and create all symbolic links in framework bundle to link to
new version.
If copying resources directly, it is already copied to bundle before symbolic
link in Brave Framework folder is created by template.
So, trying to removing existing symbolic link failed because it is real folder.
Issue: https://github.com/brave/brave-browser/issues/207

Use bundle_data to add locale resources to brave framework bundle

---

package.json

This commit hardcodes jsdom version 11.0.4 in package.json since this is the latest version that works for us. 11.0.5 breaks. See previous commit for error log.

Hardcode jsdom 11.0.4 in package.json

---

webpack/dev.config.js

This matches production config https://github.com/brave/brave-extension/blob/master/webpack/prod.config.js#L13
test plan:
* no terminal warnings regarding dev mode should be shown

supress webpack warning regarding dev mode

---

app/components/braveShields/braveShields.tsx
app/components/braveShields/braveShieldsStats.tsx
app/state/shieldsPanelState.ts
app/theme.ts
app/types/state/shieldsPannelState.ts
package.json
test/app/actions/shieldsPanelActionsTest.ts
test/app/background/reducers/shieldsPanelReducerTest.ts
test/app/components/braveShields/braveShieldsHeaderTest.tsx
test/app/components/braveShields/braveShieldsStatsTest.tsx
test/app/state/shieldsPanelStateTest.ts
test/testData.ts
yarn.lock

fix https://github.com/brave/brave-browser/issues/202
**Test plan:**
1. `yarn test-unit` as several tests changed
2. `yarn test-unit -- --grep="braveShieldsStats component"` for component changes
3. `yarn test-unit -- --grep="RESOURCES_BLOCKED"` for state changes
**Manual test plan:**
1. Clicking over stats should show a list of blocked resources if any

add support to show blocked resources by clicking on stats

---

app/components/braveShields/braveShieldsControls.tsx
app/components/braveShields/braveShieldsFooter.tsx
app/components/braveShields/braveShieldsStats.tsx
app/theme.ts
package.json
yarn.lock

follow-up of #35 
fix https://github.com/brave/brave-browser/issues/319
**Test Plan:**
(for #35)
* in shields, click on blocked stats twice should toggle on/off state and show/hide resources blocked
* above feature should have the pointer cursor
**Test Plan:**
(for https://github.com/brave/brave-browser/issues/319)
* No text inside shields should be selectable (not applicable to blocked resources URLs)

minor shields improvements

---

package-lock.json
package.json

this was preventing builds from running due to a mismatch between minor/patch.
Interestingly, this error only happens with `npm` and not with `yarn`
STR:
1. Clone this repo
2. `npm i` && `npm run build` (has to be with `npm` -- **not yarn**)
3. see build breaking
4. apply this change
5. build should run ok

stick with @types/react on 16.4.2

---

app/views/braveShieldsPanel.pug

fix https://github.com/brave/brave-browser/issues/53
**Test Plan:**
1. Toggle `Advanced Options` in shields
2. Extension should update its height based on its content (no extra whitespace at the bottom)

fix shields nor shrinking when advanced opt is hidden

---

app/background/reducers/shieldsPanelReducer.ts

fix https://github.com/brave/brave-browser/issues/470
Test Plan:
1. websites with resources blocked should show browserAction badge icon
2. websites without resources blocked should not show the browserAction badge. i.e. about pages

do not show badge text if there are no resources blocked

---

app/components/braveShields/braveShieldsStats.tsx

fix https://github.com/brave/brave-browser/issues/419
fix https://github.com/brave/brave-browser/issues/429
**Test Plan #1:** (as described in https://github.com/brave/brave-browser/issues/419)
1. Visit wikipedia.org in a new tab
2. Ensure shields shows badge as 0
3. Open shields, you can click on all shields stats even though it shows 0 **but it should not show any resource blocked as there's none**.
**Test Plan #2:** (as described in https://github.com/brave/brave-browser/issues/429)
1. Visit icloud.com in a new tab and change to Block all fingerprinting
2. See blocked count in shields
3. Visit nytimes.com in the same tab
4. Ensure there are no fingerprint blocked items
5. Click on 0 Fingerprint blocked,. **should not show any resource blocked as there's none**

do not allow showing resources blocked if there's none

---

app/background/api/browserActionAPI.ts
app/background/api/shieldsAPI.ts
app/components/braveShields/braveShields.tsx
app/components/braveShields/braveShieldsControls.tsx
app/components/braveShields/braveShieldsHeader.tsx
app/helpers/urlUtils.ts
test/app/background/api/shieldsAPITest.ts
test/app/components/braveShields/braveShieldsHeaderTest.tsx
test/app/helpers/urlUtilsTest.ts

fix brave/brave-browser#169
Test Plan:
covered by automated tests
Manual Test Plan:
Any website using protocols other than `http://`/`https://` such as `chrome://` or `file://` should have shields disabled without the option to enable it

disable shields for any protocol other than http or https

---

app/background/reducers/shieldsPanelReducer.ts
app/helpers/arrayUtils.ts
app/state/shieldsPanelState.ts
app/types/state/shieldsPannelState.ts
test/app/background/reducers/shieldsPanelReducerTest.ts
tsconfig.json

fix https://github.com/brave/brave-browser/issues/420
Test Plan:
covered by automated tests

do now allow duplicated items for resources blocked

---

app/components/braveShields/braveShields.tsx
app/components/braveShields/braveShieldsFooter.tsx
test/app/components/braveShields/braveShieldsFooterTest.tsx

closes brave/brave-browser#561
closes brave/brave-browser#417
Test Plan:
covered by automated tests
Manual Test Plan:
* Clicking on settings should go to chrome://setings
* Clicking on reload should reload the page
* Can't drag any of both options to the page (preventing bug brave/brave-browser#417)

support open settings and reload actions 

---

app/components/braveShields/braveShieldsHeader.tsx
app/components/noScript/noScript.tsx
app/theme.ts

Seems like the current cr version forces the scrollbar whenever content overlflows the container. This was always this way except for MacOS but this seems to have changed. 
Since extensions can't have more than 600px height solution was to reduce padding so we hit <=600px. This should fix the issue across all platforms.
fix https://github.com/brave/brave-browser/issues/222

prevent scrollbar in the extension container across OSes

---

BUILD.gn
app/background/api/cosmeticFilterAPI.ts
app/background/events/cosmeticFilterEvents.ts
test/app/background/api/cosmeticFilterAPITest.ts

Status: Ready to be merged.
Specifying for things to `runAt: document_start` in the `manifest.json` is not sufficient, each `chrome.tabs.insertCSS` call must include the `runAt` property as well. 
Otherwise, it will default to `document_idle`. This causes flickering.
Read more here: https://developer.chrome.com/extensions/tabs
I'm not sure if I should be merging the huge `package-lock.json` file, but I did a rebase off of `brave/brave-extension:master` and a fresh `npm i`. Please let me know if I should not check this in.
To include in this PR:

Remove Flickering and Fix Context Menu Display

---

app/background/api/cosmeticFilterAPI.ts
app/background/reducers/cosmeticFilterReducer.ts
app/background/reducers/shieldsPanelReducer.ts
app/types/state/shieldsPannelState.ts

Fix https://github.com/brave/brave-browser/issues/845
Fix https://github.com/brave/brave-browser/issues/846
[state].GetActiveTabData can return undefined from state yet the type did not reflect this even though some calls, but not all calls, handled it.
cosemtic filter list was being read before it was set in storage.

Handle no active tab in state and no cosmetic filter list in storage

---

app/background/reducers/cosmeticFilterReducer.ts
app/background/reducers/shieldsPanelReducer.ts
test/app/background/reducers/cosmeticFilterReducerTest.ts
test/app/background/reducers/shieldsPanelReducerTest.ts

fix https://github.com/brave/brave-browser/issues/429
`onBeforeNavigate` sometimes fire too soon and stats are reset when some resources are still being blocked -- leading next page to inherit its blocked resources.
Test Plan:
described in https://github.com/brave/brave-browser/issues/429#issue-335822438
Tests are updated and CI should also pass.

defer reset of resource and stats blocked to the onCommitted event

---

.vscode/settings.json

If you use VSCode, this commit fixes pasting/auto-linting from vscode/typescript addon. It will no longer try to use double-quotes, semi-colons, or 4 space tabs (default) and show up with all the TypeScript linting errors.
This is referring to the Slack message from @petemill: 
> Looks like this could all be 1 commit. 2 actually, considering the VScode should be a separate commit

Add vscode settings for linting

---

app/background/reducers/shieldsPanelReducer.ts

When browser launched with single tab(ex, https://www.google.com),
it's shields icon is in disabled state.
When browser is newly launches, many actions call `updateShieldsIcon()`.
At this time, there is no Tab object for current active tab
because initial `requestShieldPanelData` isn't finished yet.
That means there is no Tab object for current active tab in state.
Because of this, `setIcon()` can't be called by `updateShieldsIcon()`.
To fix this, shields icon is updated when shields panel data is updated.
Close https://github.com/brave/brave-browser/issues/1202
**EDIT by Cezar:**
also fixes https://github.com/brave/brave-browser/issues/505

Fix shields icon is in disabled state when browser launches

---

app/manifest.dev.json
app/manifest.prod.json

Matches the behavior of `browser-laptop` which you can see here:
https://github.com/brave/browser-laptop/blob/41e46f9ce7e0d4f7a558646f377e40d29d0e101d/app/extensions.js#L36-L216
This should help in solving https://github.com/brave/brave-browser/issues/1198
Auditors: @bridiver, @diracdeltas

Add incognito to the extension manifest and set to split mode

---

app/background.ts
app/background/api/shieldsAPI.ts
app/types/global/chrome.d.ts
test/app/background/api/shieldsAPITest.ts
test/testData.ts

Use braveShields's contentSetting method instead of chrome.contentSetting.
This will enable user able to edit shields setting.
So far, user can't edit shields setting because chrome doesn't allow editing configuration set by extension.
Our new methods stores configuration to user preference store instead of extension store.
This PR should be merged after reviewing https://github.com/brave/brave-core/pull/439.
Issue https://github.com/brave/brave-browser/issues/232

Use braveShields's contentSetting method for shield configuration

---

app/background/api/shieldsAPI.ts

Fixes https://github.com/brave/brave-browser/issues/1198
_Known issue: content settings from public windows are NOT inherited into private windows. ex: if you visit https://www.dailymail.co.uk and disable shields in a tab and then open a new private window, that shields off setting is not propagated to the private window. This is a separate bug that needs to be tracked which was not caused by this PR._
_If this PR is approved/merged, I will create an issue to track that problem_
1. Get latest `brave-browser` (master branch)
2. Update `package.json` to have branch `content-settings-add-scope` for `brave-core`
3. Run `npm run init` or `npm run sync -- --all`
4. Build with `npm run build`
5. Launch with `npm start`
1. Have a fresh profile and launch Brave
2. Open a new private window
3. …

Add scope to methods which modify content settings

---

app/components/braveShields/footer.tsx

needs https://github.com/brave/brave-core/pull/785
fix https://github.com/brave/brave-browser/issues/1959
Test Plan: link to global shields settings should go to brave://settings/shields

add deeplink to the shields section

---

app/background/api/shieldsAPI.ts
app/helpers/urlUtils.ts
test/app/helpers/urlUtilsTest.ts

When url includes port w/o scheme, chromium parses it as an invalid
port number. Because of this, contents setting is failed.
To fix this, scheme is preserved when url has port number.
Fix https://github.com/brave/brave-browser/issues/1896

Fix shields isn't toggled when url has port number

---

package-lock.json
package.json
test/app/background/api/browserActionAPITest.ts
test/app/background/api/cosmeticFilterAPITest.ts
test/app/background/api/tabsAPITest.ts
test/app/background/reducers/cosmeticFilterReducerTest.ts
test/app/background/reducers/shieldsPanelReducerTest.ts

Fix https://github.com/brave/brave-browser/issues/3262
Right now brave-core includes brave-extension at the following commit refs:
master - d1a956accdbb38a51bede5d463edb299012d0fe8
0.61.x - 70550a1619139459119f472c18a03dc12c3ed5f2 (diff https://github.com/brave/brave-extension/compare/master..70550a1)
0.60.x - 70550a1619139459119f472c18a03dc12c3ed5f2
0.59.x - 038a43af5294150d48ce94a326290f70aa001cd0 (diff https://github.com/brave/brave-extension/compare/master..038a43a)
So we may need to cherry-pick this fix in to branches from those shas if we don't want to bring in any other brave-extension changes to those brave-core branches.
This is a low-risk change since it only affects unit tests (which all pass)

Update sinon dependency to 7.2.3
